# Generated by Django 5.0.6 on 2024-05-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_commentary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="post",
            new_name="task",
        ),
    ]
