# Generated by Django 5.0.6 on 2024-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_rename_post_commentary_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
