# Generated by Django 5.0.6 on 2024-05-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_worker_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
    ]
