# Generated by Django 5.0.6 on 2024-05-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_position_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["name", "-deadline"]},
        ),
    ]
